/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 08-Apr-2019 15:13:52
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 11
const int Cascade_NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const float Cascade_Num[MWSPT_NSEC][3] = {
  {
    7,              0,              0
  },
  {
    0.02031565644,-4.313548743e-06, -0.02029993571 
  },
  {
                1,              0,              0 
  },
  {
   0.008616184816,  0.01723925397, 0.008623070084 
  },
  {
                1,              0,              0 
  },
  {
   0.007754703984,  0.01550703682, 0.007752335165 
  },
  {
                1,              0,              0 
  },
  {
      0.102649875,  -0.2053464353,   0.1026965752 
  },
  {
                1,              0,              0 
  },
  {
     0.3544031084,  -0.7087445259,   0.3543414474 
  },
  {
                1,              0,              0 
  }
};
const int Cascade_DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const float Cascade_Den[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   -1.568947196,   0.9765557647 
  },
  {
                1,              0,              0 
  },
  {
                1,    -1.54675734,   0.9804962873 
  },
  {
                1,              0,              0 
  },
  {
                1,    -1.59688592,   0.9815012813 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.539639592,   0.9923905134 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.620438457,   0.9930179119 
  },
  {
                1,              0,              0 
  }
};
