/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 05-Apr-2019 11:17:50
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 11
 * Denominator Length  : 11
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int NL = 11;
const float DF2_Num[11] = {
  6.465334934e-09,              0,-3.232667467e-08,              0,6.465334934e-08,
                0,-6.465334934e-08,              0,3.232667467e-08,              0,
  -6.465334934e-09
};
const int DL = 11;
const float DF2_Den[11] = {
                1,   -7.872668266,    29.71321106,   -70.03581238,    113.6478195,
     -132.3376312,    111.9167862,   -67.91855621,    28.37606621,   -7.403879166,
     0.9261333942
};
